### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by MicahZoltu** [Kintaro/SnappySharp#2]
It appears there is no license for this, I would like to use it in a project but without a license, it is too risky.  Something compatible with an Apache 2.0 project would be ideal.

**Comment by Kintaro** [comment]
Oh sorry, totally forgot about that project. I'll add a license in a few minutes New BSD acceptable?

**Comment by MicahZoltu** [comment]
Sure.

**Comment by Kintaro** [comment]
Done. Go ahead :)
